version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8-browsers

    working_directory: ~/IntoTommorrowSPA

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install-dependencies
          command: npm install

      - run:
          name: install-chrome-for-protractor-tests
          command: wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
          sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
          sudo apt update && sudo apt install -yq google-chrome-stable

      - run:
          name: unit-tests
          command: npm run test

      - run:
          name: system-tests
          command: npm run e2e

      - save_cache:
          name: save-node-modules
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - save_cache:
          name: save-dist
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
              - dist
  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
